### ISSUE TITLE
Title pictures mis-scaled on wider-than usual monitors

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/website#1]
The display resolution is 3840x2160

![Screenshot 2022-10-07 at 14 51 52](https://user-images.githubusercontent.com/1671664/194558222-eac3ab0f-9e72-4ae4-b18c-61ae0e5649ba.png)

**Comment by BlueChili** [comment]
Added an extra breakpoint for larger screen sizes in da9ed39
