### ISSUE TITLE
Update Article and Case Study page

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#20]
We need an opportunity to add a second author to a case study and an article. Now we face a situation when 2 people work on the project.
It can look like this:
[Example](https://drive.google.com/file/d/1BZZH6DN7LEVbQugwvP6_8fDt_XDCCWMx/view?usp=sharing)

**Comment by BlueChili** [comment]
Addressed in  [3326672](https://github.com/fivexl/website/commit/33266729c239c3746661eac629c9b996fc353fdc)  changes nothing for the handling of single author, the feature relies in the **author_id** frontmatter param, so a single author remains the same, and multiple authors get input as an array of strings:

```
author_id: [  "author#1", "second author" ]
```

**Comment by relevanto** [comment]
@BlueChili It would be useful for the future to have the opportunity to change the order of authors. Now it seems that despite the order in visual studio, it displays alphabetically.  Maybe I'm doing something wrong?
<img width="600" alt="Screenshot 2022-12-08 at 14 49 39" src="https://user-images.githubusercontent.com/2032530/206463372-23650177-06bd-4b8b-b010-18708cd51447.png">
<img width="427" alt="Screenshot 2022-12-08 at 14 49 49" src="https://user-images.githubusercontent.com/2032530/206463392-0a3d3496-e344-4f0b-a5c9-e2f4fbc3e1dd.png">

**Comment by BlueChili** [comment]
@relevanto Yeah, can confirm the behaviour is consistent. will rework it to keep the ordering of the authors as they are defined in the frontmatter.
