### ISSUE TITLE
Services page: adjusting "our happy customers" as in the design 

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#41]
- [x] The title "Our happy customers" should be lower. Now it's too close to the upper section. 

- [x] Put the order of colors as on the design: blue, violet, raspberry, and pink to make a correct wave. 

- [x] Buttons "read more" should be on the same level at the bottom of the cards. 

- [x] Change font for [secondary texts on the cards](https://drive.google.com/file/d/1oNPcR57Eu8EJDf6dyUWvApzTukIRxVnD/view?usp=sharing). I think It is a Regular Monsterrat in the design.  

- [x] The cards stand closer to each other in the design, but there is no big space at the sides. Can we do the same, or is there some obstacle?
- [x] Speech mark should be at the [top left ](https://drive.google.com/file/d/1DKqyV3KNuoI1LFt9jHjp7bzeCFsJx81K/view?usp=sharing), and phrases start with them.
- [x]  In the design, the top line is always the name of the company Firi, Qameta, etc, and the second is Case Study; maybe this is simply solved by line wrapping.

**Comment by BlueChili** [comment]
List of changes implemented in 26a1d70
