### ISSUE TITLE
Services page: fix the mobile version

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#45]
- [x] fix problems with the [menu](https://drive.google.com/file/d/1isPlVvaMofFK6C8jsPX14DyZ103P9j_0/view?usp=sharing)

**Comment by BlueChili** [comment]
I apologize, I was aware of this  but still managed to slip by, addressed in bd59a6f

**Comment by relevanto** [comment]
Now the menu looks good, but could you please make to switching blue color when we you select different points of [menu](https://drive.google.com/file/d/1FQ3WystyZ2JngB2sVXtNsxpWQXW53w_J/view?usp=sharing) For example when I am in a Services section, I want to highlight Services, when I am in blog - highlight blog.

**Comment by BlueChili** [comment]
@relevanto Just changing the color hurts the legibility of the item when working with a 
![transparent background navigation bar](https://github.com/fivexl/website/assets/1210666/ca201be8-aa4e-4c4f-95fb-b11bcc5ffcd2)
I could change the navigation to use a white background as in the desktop design to sidestep the issue, kill a bit of visual attractive but adds the active color in a consistent manner

**Comment by BlueChili** [comment]
Also feel free to tell me my eyes are not working all that well, and that the link looks just fine :)

**Comment by BlueChili** [comment]
@relevanto Color for active navigation item implemented in a1a4a3f

Circumvented the legibility issue by applying the default header styling on larger sizes.
