### ISSUE TITLE
Create a Case Studies section

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#58]
Create a section on the website for Case Studies according to design.
It includes:
 The main page with an infinite scroll list https://www.figma.com/file/EQxUcRDhZyMm5Kjgs8LNgB/Case-Study-main?type=design&node-id=10649%3A225&t=wrUYgo7B7jst4yAx-1
The Case study page 
https://www.figma.com/file/Mmj50hbZ3CLWdX6jh05EVi/Case-Study?type=design&node-id=0%3A1&t=wrUYgo7B7jst4yAx-1

**Comment by BlueChili** [comment]
@relevanto Infinite scroll was added  in 0e2b663 some changes were added temporarily to demonstrate how it would work, pages contain a single item only, you will have to scroll upwards and then down, to simulate a normal user interaction.

Sorry for the contrived demo, it is smarter  to work within the constraints of existing content, than to generate a bunch of placeholder entries, only to delete them later on.

Regarding default values for the final version, 12 would be my go to number of items for each "results page" in the infinite scroll list, though the number could be raised or decreased without issue.

**Comment by relevanto** [comment]
@BlueChili I checked, and it seems everything is fine. There's just one point I've noticed, regarding the logic. Under the big banner, our latest added case study is displayed with big image. There is no need to repeat it in More case studies.

**Comment by BlueChili** [comment]
@relevanto of course, I took out the filter just to add an additional result temporarily to better demonstrate the dynamic loading of new case studies.
