### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by cageyv** [fivexl/website#6]
- Links in right menu are broken in case of space inside tag https://fivexl.netlify.app/tags/aws%20cloud
<img width="338" alt="image" src="https://user-images.githubusercontent.com/51059484/196935336-da62da5c-66cc-4fcf-9d4d-af832ab78dbf.png">

- Share to LinkedIn generate that link `https://www.linkedin.com/sharing/share-offsite/?url=%2fblog%2fhow-to-save-resources%2f`

- Share to Email generate that message `Check this article from fiveXl:/blog/how-to-save-resources/:Find out how the CloudTrail-to-Slack Terraform module by FivexL solves this problem for startups and small teams.`

- Footer Logo link to main page
<img width="341" alt="image" src="https://user-images.githubusercontent.com/51059484/196939713-cedd7bb7-01f0-494e-b1b7-aaa2d661e99b.png">

**Comment by BlueChili** [comment]
Fixed in d47dd1b
