### ISSUE TITLE
align consultants' profiles 

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#61]
Please [align](https://drive.google.com/file/d/1XmxkhAa2dADy0W7CjTH8-fZinE0KHief/view?usp=sharing)
1. Move profile to the left 
2. Make names in 2 lines at the level of the circle's midpoint.
3. Make equal margins between people and "Read more", and between people and the bottom edge of the photo. If there's only one person, we don't move anything, we just remove the second one.

**Comment by BlueChili** [comment]
@relevanto Addressed in 2cf3bf9
