### ISSUE TITLE
Reduce the distance between case studies

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#62]
The distance between the case studies is [too large](https://drive.google.com/file/d/1w-SETud4QQFQpsyeCCJMfe3X3gfaBpJw/view?usp=sharing). I would like it to be as in the [design mockup](https://www.figma.com/file/EQxUcRDhZyMm5Kjgs8LNgB/Case-Study-main?type=design&node-id=10649%3A225&mode=design&t=GfJgytmmL1l8QfFl-1), where is more compactly arranged.

**Comment by BlueChili** [comment]
Couple comments on this one, as I see this going either way on two different approaches:
1. In commit 49667db opted to add a max size to the case study items, headings have a fixed height to provide a consistent vertical positioning of the summary text below.
2. A different approach can be seen here ![here](https://github.com/fivexl/website/assets/1210666/e67d0244-bb15-4a8d-9f40-e412ae57b5ac), with the items size remaining flexible while constrained to a maximum number of 3 columns, however keeping tighter gap between elements.

Approach #1 is in the commit contents and can be seen in the deploy preview of the PR, let me know if you prefer the second approach instead.

**Comment by BlueChili** [comment]
Switched to second approach  on 84c534f
