### ISSUE TITLE
Pictures of case studies 

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#64]
1. Link the pictures of the case studies to their respective pages.
2. For More Case Studies, do not trim the 'panel_image'. Instead, use the 'alt_image'. This additional attribute was created for our initial version of the Services page. The current images may not be entirely suitable, but their square shape is more fitting for our needs. Eventually, all of these will be replaced with aesthetically pleasing square ones.

**Comment by BlueChili** [comment]
Addressed in 296d189
