### ISSUE TITLE
Links from titles

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#67]
Set the links from [the title and from the large image](https://drive.google.com/file/d/18q-HIjQV57o-MgzhVa7lnZbetHo5UOps/view?usp=sharing) to the case study page.
And from [case studies titles ](https://drive.google.com/file/d/1Mxff2R3IBdRJXRtU9liukuce9jvK7ik6/view?usp=sharing)

**Comment by BlueChili** [comment]
@relevanto Addressed in 6b05207
