### ISSUE TITLE
layout. mobile

### ISSUE THREAD

**Issue by cageyv** [fivexl/website#7]
- main page
<img width="471" alt="image" src="https://user-images.githubusercontent.com/51059484/196937095-69836d10-4a94-49f3-abe5-30fb35fe2479.png">
- services 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/51059484/196937326-93d332a7-ebb6-4748-a089-0f8aa7f97c5a.png">
- blog , pictures too left 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/51059484/196938102-9546edbc-b40c-44a1-b892-fc7518f28262.png">
- author part
<img width="452" alt="image" src="https://user-images.githubusercontent.com/51059484/196939261-93deafec-f53a-41d5-92fc-93710ebcaf07.png">

**Comment by BlueChili** [comment]
Fixed in 0406e93
Regarding the main page layout bug, I was not able to replicate it, I did test in-device using three different Iphones and a couple Android devices

**Comment by cageyv** [comment]
Main page layout bug appears only in Developer View simulator and not appears on real devices 
Let's say, that it is not exist anymore :)
