### ISSUE TITLE
Distance between Benefits, Our Happy Customers and Footer 

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#73]
Let's halve [the distance](https://drive.google.com/file/d/1bGMnhVX2E6tpVMiPPzreCAvvWAJ5VB_N/view?usp=sharing) between the 'Benefits' and 'Our Happy Customers' sections.
And let's increase the distance between 'Our Happy Customers' and the footer, so it ends up being the same as the distance between the 'Benefits' and 'Our Happy Customers' sections.

**Comment by BlueChili** [comment]
Addressed in b93f995
