### ISSUE TITLE
fonts

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#74]
Let's set the same font size of the main texts [here](https://drive.google.com/file/d/1V6kBM_6pVXHMT5GTMDPjveV1lSWlxacR/view?usp=drive_link), [here](https://drive.google.com/file/d/1_tExWJFYLxs0RKxHd-MES4hNH69F8Hnv/view?usp=drive_link) and [here](https://drive.google.com/file/d/1ZruKS6JBh9GninsWqEoVfO2yZHPvIvhx/view?usp=drive_link).

**Comment by BlueChili** [comment]
Addressed in da395dd

**Comment by relevanto** [comment]
It seems to me that the line spacing in [the text next to the photo](https://drive.google.com/file/d/1yG2MI0i8nraZn33VS1Slt8_tWAkZGQB_/view?usp=sharing) and [the About New Stream text](https://drive.google.com/file/d/15p_n62PnkqT59sr6EWqr-txqdOrlMs02/view?usp=drive_link) are different after all. Let's make this text look the same as the About New Stream text.

**Comment by BlueChili** [comment]
Topic branch merged
