### ISSUE TITLE
Distance around the diagram

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#75]
Please adjust the distance around the diagram. 
In [the desktop version](https://drive.google.com/file/d/12DwQRT1qdncohLIdrDD9OSrdxJwVngXe/view?usp=sharing), the top margin is slightly larger than after the diagram. And [in the mobile version](https://drive.google.com/file/d/1qY4NmvGo0QVegZ55v9eJZju9sNo5-672/view?usp=sharing), the difference is even more noticeable. Let's make the margins before and after the diagram the same.

**Comment by BlueChili** [comment]
Fixed in fbe2e29

**Comment by BlueChili** [comment]
Topic branch merged
