### ISSUE TITLE
Create a link to the author's page by clicking on the photo and name

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#8]
Create a link to the author's page by clicking on the photo and name
<img width="628" alt="Screenshot 2022-10-24 at 10 46 52" src="https://user-images.githubusercontent.com/2032530/197487175-e02f0b08-ff59-4ebb-b3d5-10982d9d1bb4.png">

**Comment by BlueChili** [comment]
Fixed in 9c45b16
