### ISSUE TITLE
Warn message 

### ISSUE THREAD

**Issue by relevanto** [fivexl/website#89]
Please take a look, I have a [message appearing](https://drive.google.com/file/d/1HIyX5dSsBK9jmYi6cyzaFI-d3XL8rDl_/view?usp=sharing): 'WARN found no layout file for "json" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.' Do I need to do something about this?

**Comment by BlueChili** [comment]
It complains because a Json layout exists for case-studies and other types of content don't have one, this warning is 100% safe to ignore
